[project]
name = "titanoboa"
version = "0.1.7"
description = "A Vyper interpreter"
#authors = []
license = { file = "LICENSE" }
readme = "README.md"
#homepage = "https://github.com/vyperlang/titanoboa"
#repository = "https://github.com/vyperlang/titanoboa"
#documentation =

keywords = ["ethereum", "evm", "smart contract", "development"]

classifiers = ["Topic :: Software Development"]

# Requirements
dependencies = [
    "vyper > 0.3.9",
    "eth-stdlib",
    "eth-abi",
    "py-evm>=0.7.0a4",
    "eth-typing",
    "hypothesis",
    "pytest",
    "rich",

    # required for forking:
    "requests",

    # required for networked accounts
    "eth-account",
]

[project.optional-dependencies]
forking-recommended = ["plyvel", "ujson"]

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["boa*"]

[tool.pytest.ini_options]
markers = ["ignore_isolation: Do not preserve state during tests"]

#[dev-dependencies]
#black = { version = "^18.3-alpha.0", python = "^3.6" }
