[project]
name = "titanoboa"
version = "0.1.2"
description = "Experimental Vyper interpreter"
#authors = []
license = { file = "LICENSE" }
readme = "README.md"
#homepage = "https://github.com/vyperlang/titanoboa"
#repository = "https://github.com/vyperlang/titanoboa"
#documentation =

keywords = ["ethereum", "evm", "smart contract", "development"]

classifiers = ["Topic :: Software Development"]

# Requirements
dependencies = [
    "vyper @ git+https://github.com/vyperlang/vyper@09f376353ea287c55390a9c53de7547c7ece66c1",
    "eth-abi",
    "py-evm",
    "eth-typing",
]

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["boa*"]

#[dev-dependencies]
#black = { version = "^18.3-alpha.0", python = "^3.6" }
