[project]
name = "titanoboa"
version = "0.1.6"
description = "Experimental Vyper interpreter"
#authors = []
license = { file = "LICENSE" }
readme = "README.md"
#homepage = "https://github.com/vyperlang/titanoboa"
#repository = "https://github.com/vyperlang/titanoboa"
#documentation =

keywords = ["ethereum", "evm", "smart contract", "development"]

classifiers = ["Topic :: Software Development"]

# Requirements
dependencies = [
    "vyper @ git+https://github.com/vyperlang/vyper.git@8ebabc5ce277942ee470845e2d04df5f8a2e6ad6",
    "eth-abi",
    "py-evm",
    "eth-typing",
    "hypothesis",
    "pytest",
#'eth-stdlib; python_version >= "3.10"',

# required for forking:
    "requests",
]

[project.optional-dependencies]
forking-recommended = [
    "plyvel",
    "ujson",
]

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["boa*"]

[tool.pytest.ini_options]
markers = ["ignore_isolation: Do not preserve state during tests"]

#[dev-dependencies]
#black = { version = "^18.3-alpha.0", python = "^3.6" }
