name: unitary

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unitary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    name: "unit tests: python ${{ matrix.python-version }}"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Requirements
        run: |
          pip install -r dev-requirements.txt
          pip install .

      - name: Run Unit Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          # pass internals to pytest-cov, since we are testing a pytest plugin.
          # See https://github.com/pytest-dev/pytest-cov/blob/2c9f2170/docs/plugins.rst
          COV_CORE_SOURCE: boa
          COV_CORE_CONFIG: .coveragerc
          COV_CORE_DATAFILE: .coverage.eager
        run: >-
          pytest
          --cov=boa
          --cov-append
          --cov-report term-missing:skip-covered
          --cov-fail-under=70
          tests/unitary/

  anvil:
    name: "integration tests (anvil)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Requirements
        run: |
          pip install -r dev-requirements.txt
          pip install .

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Networked Tests against anvil
        # run separately to clarify its dependency on outside binary
        run: pytest -n auto tests/integration/network/anvil/
